version: "3"
volumes:
  db-data:
services:
  frontend1:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args: 
        - BACKEND=?
        - KEYCLOACK=?
        - KEYCLOACK_CLIENT_ID=?
    container_name: demo-frontend1
    ports: 
      - "80:80"     
    depends_on: 
      - backend1
  backend1:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        - ENV=production
        - DB_IP=mysql
        - DB_PORT=3306
        - DATABASE_TYPE=MYSQL
        - DB_USERNAME=app
        - DB_PASSWORD=123
        - DB_NAME=crud-angular-spring-boot
    container_name: demo-backend1
    restart: on-failure:5
    ports: 
      - "8080:8080"       
    depends_on:
      - mysql
  mysql:
    environment:
      - MYSQL_USER=app
      - MYSQL_PASSWORD=123
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=crud-angular-spring-boot
    container_name: demo-mysql
    image: mysql:8.0.16
    volumes:
      - db-data:/var/lib/mysql:rw
