version: "3"
volumes:
  db-data:
services:
  frontend1:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args: 
        - BACKEND=http://localhost:8080
        - KEYCLOACK=http://localhost:8081/auth/realms/master/protocol/openid-connect/token
        - KEYCLOACK_CLIENT_ID=demo-angular
    container_name: demo-frontend1
    ports: 
      - "80:80"     
    depends_on: 
      - backend1
      - keycloak
  keycloak:
      image: jboss/keycloak:latest
      ports: 
        - "8081:8080"
      restart: "unless-stopped"
      depends_on:
        - backend1
      environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: 123456
        KEYCLOAK_LOGLEVEL: DEBUG
        DB_ADDR: mysql
        DB_PORT: 3306
        DB_USER: keycloak
        DB_PASSWORD: keycloak123
        DB_DATABASE: keycloak_db
  backend1:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        - ENV=production
        - DB_IP=mysql
        - DB_PORT=3306
        - DATABASE_TYPE=MYSQL
        - DB_USERNAME=app
        - DB_PASSWORD=123
        - DB_NAME=crud-angular-spring-boot
    container_name: demo-backend1
    restart: on-failure:5
    ports: 
      - "8080:8080"       
    depends_on:
      - mysql
  mysql:
    environment:
      - MYSQL_USER=app
      - MYSQL_PASSWORD=123
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=crud-angular-spring-boot
    container_name: demo-mysql
    image: mysql:5.7.26
    volumes:
      - db-data:/var/lib/mysql:rw
      - ./keycloak.sql:/docker-entrypoint-initdb.d/keycloak.sql

